### ISSUE TITLE
Cannot build application

### ISSUE THREAD

**Issue by Olimov-Umidbek** [moleculer-java/moleculer-spring-boot-demo#1]
Hello,
I cannot build application, IDE(IDEA) doesn't recognize MoleculerApplication(Main Application). How can I solve this problem ?

**Comment by berkesa** [comment]
Yes, it's an Eclipse Project, not an IntelliJ Project. To compile this project under IntelliJ, try the following:

1.) Download the demo project from here:
https://github.com/moleculer-java/moleculer-spring-boot-demo/archive/master.zip

2.) Create a new, empty **GRADLE** project under IntelliJ IDEA and name it "Moleculer Demo".

3.) Copy the **"src", "installer"** and **"gradle"** directories from the ZIP into the project dir.

4.) Copy the **"build.gradle"**, **"gradlew"**, **"gradlew.bat"**, **"settings.gradle"** from the ZIP into the project dir.

Hopefully after that the project can be compiled. To run, the following parameters must be specified in the Run Configuration:

- **Main class:** services.moleculer.config.MoleculerRunner
- **VM options:** -Djava.library.path="installer/bin" -Dlogging.config="classpath:logging-development.properties" -Djava.net.preferIPv4Stack=true -Dspring.profiles.active=development
- **Program arguments:** my.application.MoleculerApplication

**Comment by berkesa** [comment]
.... or download Eclipse as described below:
https://github.com/moleculer-java/moleculer-spring-boot-demo#compile-and-run-from-source-code

**Comment by berkesa** [comment]
When using IntelliJ IDEA, the following two dependencies had to be included in the "build.gradle" file (I don't know why, Eclipse didn't need it):

	// DataTree core (required)
	compile group: 'com.github.berkesa', name: 'datatree-core', version: '1.0.11'

	// Moleculer (required)
	compile group: 'com.github.berkesa', name: 'moleculer-java', version: '1.2.4'

**Comment by berkesa** [comment]
If you have a subdirectory named ".idea" in the project directory, IntelliJ Idea will recognize it as a java project. I created such a library, so the project can be imported under both Eclipse and Idea.

https://github.com/moleculer-java/moleculer-spring-boot-demo#compile-and-run-from-source-code-intellij-idea

**Comment by Olimov-Umidbek** [comment]
Thanks for your feedback, I tried but in this path MoleculerApplication class not found:
my.application.MoleculerApplication

**Comment by Olimov-Umidbek** [comment]
Thanks a lot. All of them working correctly!
